url: "https://pi-tv.github.io"

collections:
  docs:
    output: true
    directory: /

defaults:
  - scope:
      type: docs
    values:
      layout: doc


markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-sitemap
  
