url: "https://pi-tv.github.io"

layout: post

collections:
  docs:
    output: true
    relative_directory: /
    permalink: /:title

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-sitemap
  
